### ISSUE TITLE
Ensure configured taps are tapped

### ISSUE THREAD

**Issue by rmchale** [geerlingguy/ansible-role-homebrew#100] opened 2018-07-09 14:55 UTC
I have this error on multiple machines.
```
TASK [geerlingguy.homebrew : Ensure configured taps are tapped.] *********************
failed: [127.0.0.1] (item=caskroom/cask) => {"failed": true, "item": "caskroom/cask", "msg": "added: 0, unchanged: 0, error: failed to tap: caskroom/cask"}
failed: [127.0.0.1] (item=caskroom/versions) => {"failed": true, "item": "caskroom/versions", "msg": "added: 0, unchanged: 0, error: failed to tap: caskroom/versions"}
```

**Comment by elliotweiser** [comment] 2018-07-09 15:58
Hey @rmchale. I'm going to close this as a duplicate of #93. Please ensure a) that you're using the latest version of this role and b) that you are tapping correctly named taps.

In the future, it would be helpful if you provided more information, e.g. version of the role, Ansible version, Homebrew version, and maybe a code snippet.

**Closed by elliotweiser** 2018-07-09 15:58 UTC
