### ISSUE TITLE
Homebrew git clone fails with "'/usr/local' already exists and is not an empty directory"

### ISSUE THREAD

**Issue by surfer190** [geerlingguy/ansible-role-homebrew#28] opened 2016-06-19 10:48 UTC
So the git clone fails if homebrew is already there

```
 _____________________________________________________________ 
< TASK [geerlingguy.homebrew : Ensure homebrew is installed.] >
 ------------------------------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/git clone --origin origin --branch master --depth 1 git://github.com/Homebrew/homebrew.git /usr/local", "failed": true, "msg": "fatal: destination path '/usr/local' already exists and is not an empty directory.", "rc": 128, "stderr": "fatal: destination path '/usr/local' already exists and is not an empty directory.\n", "stdout": "", "stdout_lines": []}
```

**Comment by geerlingguy** [comment] 2016-06-29 15:22
It's working for me when repeatedly running a playbook using the role—it might be that the installed copy of homebrew wasn't installed via `git clone` but through some other means, and when Ansible is checking on the repository it's not seeing a `.git` directory.

This role assumes you've installed homebrew via a git clone, and the homebrew directory is a valid git repo... if it's not, then the role won't be able to keep it updated or check status.

**Comment by geerlingguy** [comment] 2016-06-29 15:27
But marking as a dupe of #18 — since this is basically the same overriding issue.

**Closed by geerlingguy** 2016-06-29 15:27 UTC
