### ISSUE TITLE
Some brew packages (ant, gradle...) depends on java in brew cask

### ISSUE THREAD

**Issue by chshawkn** [geerlingguy/ansible-role-homebrew#74] opened 2017-07-13 19:29 UTC
Need a mechanism that run brew cask install before brew install.

**Comment by geerlingguy** [comment] 2017-07-17 04:32
Thanks for submitting an issue! It looks like this may be a duplicate of https://github.com/geerlingguy/ansible-role-homebrew/issues/38 — and there's a PR (#58) that should hopefully fix things once it's merged.

**Closed by geerlingguy** 2017-07-17 04:32 UTC
